var classes = [
    {
        "name": "App\\Fight\\FightSimulation",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "start",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Fight\\AbstractSimulation"
        ],
        "parents": [
            "App\\Fight\\AbstractSimulation"
        ],
        "lcom": 1,
        "length": 39,
        "vocabulary": 12,
        "volume": 139.81,
        "difficulty": 15,
        "effort": 2097.2,
        "level": 0.07,
        "bugs": 0.05,
        "time": 117,
        "intelligentContent": 9.32,
        "number_operators": 9,
        "number_operands": 30,
        "number_operators_unique": 6,
        "number_operands_unique": 6,
        "cloc": 1,
        "loc": 25,
        "lloc": 24,
        "mi": 69.58,
        "mIwoC": 54.33,
        "commentWeight": 15.25,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 196,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 196,
        "package": "App\\Fight\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Fight\\AbstractSimulation",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWinner",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "swap",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "duel",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPlayersOrder",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "start",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 8,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Player\\PlayerInterface",
            "App\\Player\\PlayerInterface",
            "App\\PresentationModel\\PresentationModel"
        ],
        "parents": [],
        "lcom": 2,
        "length": 70,
        "vocabulary": 20,
        "volume": 302.53,
        "difficulty": 16,
        "effort": 4840.56,
        "level": 0.06,
        "bugs": 0.1,
        "time": 269,
        "intelligentContent": 18.91,
        "number_operators": 22,
        "number_operands": 48,
        "number_operators_unique": 8,
        "number_operands_unique": 12,
        "cloc": 15,
        "loc": 64,
        "lloc": 49,
        "mi": 78.77,
        "mIwoC": 44.68,
        "commentWeight": 34.08,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.21,
        "relativeSystemComplexity": 121.21,
        "totalStructuralComplexity": 726,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 727.25,
        "package": "App\\Fight\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Config\\Settings",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 10,
        "lloc": 7,
        "mi": 208.52,
        "mIwoC": 171,
        "commentWeight": 37.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Config\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\PresentationModel\\AbstractFightView",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "displayGameHeader",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "displayWelcome",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "displayFightStarted",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "displayRound",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "displayHitInfo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "displayWinner",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 6,
        "length": 20,
        "vocabulary": 12,
        "volume": 71.7,
        "difficulty": 0.64,
        "effort": 45.63,
        "level": 1.57,
        "bugs": 0.02,
        "time": 3,
        "intelligentContent": 112.67,
        "number_operators": 6,
        "number_operands": 14,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 28,
        "lloc": 28,
        "mi": 55.3,
        "mIwoC": 55.3,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.5,
        "relativeSystemComplexity": 6.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 39,
        "totalSystemComplexity": 39,
        "package": "App\\PresentationModel\\",
        "pageRank": 0.08,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\PresentationModel\\AbstractPlayerView",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "display",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "displayStatistics",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Player\\PlayerInterface",
            "App\\Player\\PlayerInterface"
        ],
        "parents": [],
        "lcom": 2,
        "length": 21,
        "vocabulary": 8,
        "volume": 63,
        "difficulty": 2.83,
        "effort": 178.5,
        "level": 0.35,
        "bugs": 0.02,
        "time": 10,
        "intelligentContent": 22.24,
        "number_operators": 4,
        "number_operands": 17,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 7,
        "loc": 26,
        "lloc": 19,
        "mi": 95.37,
        "mIwoC": 59.37,
        "commentWeight": 36,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.31,
        "relativeSystemComplexity": 64.31,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 1.22,
        "totalSystemComplexity": 257.22,
        "package": "App\\PresentationModel\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\PresentationModel\\FightView",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\PresentationModel\\AbstractFightView"
        ],
        "parents": [
            "App\\PresentationModel\\AbstractFightView"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\PresentationModel\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\PresentationModel\\PlayerView",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "display",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\PresentationModel\\AbstractPlayerView",
            "App\\PresentationModel\\AbstractPlayerView",
            "App\\Player\\PlayerInterface",
            "self"
        ],
        "parents": [
            "App\\PresentationModel\\AbstractPlayerView"
        ],
        "lcom": 2,
        "length": 10,
        "vocabulary": 5,
        "volume": 23.22,
        "difficulty": 1,
        "effort": 23.22,
        "level": 1,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 23.22,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 66.76,
        "mIwoC": 66.76,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 9.75,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 19.5,
        "package": "App\\PresentationModel\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\PresentationModel\\PresentationModel",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getFightView",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlayerView",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\PresentationModel\\AbstractFightView",
            "App\\PresentationModel\\FightView",
            "App\\PresentationModel\\AbstractPlayerView",
            "App\\Player\\PlayerInterface",
            "App\\PresentationModel\\PlayerView"
        ],
        "parents": [],
        "lcom": 2,
        "length": 4,
        "vocabulary": 2,
        "volume": 4,
        "difficulty": 1,
        "effort": 4,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 2,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 4,
        "loc": 16,
        "lloc": 12,
        "mi": 107.08,
        "mIwoC": 72.11,
        "commentWeight": 34.97,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "package": "App\\PresentationModel\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "App\\Helpers\\Value",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 1,
        "effort": 7.92,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 7.92,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 10,
        "loc": 18,
        "lloc": 8,
        "mi": 119.61,
        "mIwoC": 73.87,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "App\\Player\\Helpers\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Player\\Statistics\\Statistics",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHealth",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setHealth",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStrength",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDefence",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSpeed",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLuck",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Player\\Statistics\\StatisticsInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 34,
        "vocabulary": 8,
        "volume": 102,
        "difficulty": 3.83,
        "effort": 391,
        "level": 0.26,
        "bugs": 0.03,
        "time": 22,
        "intelligentContent": 26.61,
        "number_operators": 11,
        "number_operands": 23,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 45,
        "loc": 86,
        "lloc": 41,
        "mi": 95.64,
        "mIwoC": 50.62,
        "commentWeight": 45.02,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5.86,
        "relativeSystemComplexity": 5.86,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 41,
        "totalSystemComplexity": 41,
        "package": "App\\Player\\Statistics\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Player\\Type",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "human",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "beast",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 2,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.5,
        "effort": 3.17,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 12.68,
        "number_operators": 2,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 10,
        "loc": 22,
        "lloc": 12,
        "mi": 113.94,
        "mIwoC": 70.71,
        "commentWeight": 43.23,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "App\\Player\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Player\\StatisticsFactory",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getForBeast",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getForHuman",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Player\\Statistics\\StatisticsInterface",
            "App\\Player\\Type",
            "self",
            "App\\Player\\Type",
            "self",
            "App\\Player\\Statistics\\Statistics",
            "App\\Player\\Statistics\\StatisticsInterface",
            "App\\Helpers\\Value",
            "App\\Helpers\\Value",
            "App\\Helpers\\Value",
            "App\\Helpers\\Value",
            "App\\Helpers\\Value",
            "App\\Player\\Statistics\\Statistics",
            "App\\Player\\Statistics\\StatisticsInterface",
            "App\\Helpers\\Value",
            "App\\Helpers\\Value",
            "App\\Helpers\\Value",
            "App\\Helpers\\Value",
            "App\\Helpers\\Value",
            "App\\Player\\Statistics\\Statistics"
        ],
        "parents": [],
        "lcom": 3,
        "length": 39,
        "vocabulary": 19,
        "volume": 165.67,
        "difficulty": 4,
        "effort": 662.68,
        "level": 0.25,
        "bugs": 0.06,
        "time": 37,
        "intelligentContent": 41.42,
        "number_operators": 9,
        "number_operands": 30,
        "number_operators_unique": 4,
        "number_operands_unique": 15,
        "cloc": 16,
        "loc": 42,
        "lloc": 26,
        "mi": 93.91,
        "mIwoC": 53.06,
        "commentWeight": 40.85,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 10.33,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 31,
        "package": "App\\Player\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Player\\Player",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getType",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatistics",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSkills",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "subtractHealth",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Player\\PlayerInterface",
            "App\\Player\\Statistics\\StatisticsInterface",
            "App\\Player\\Statistics\\StatisticsInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 9,
        "volume": 91.93,
        "difficulty": 5,
        "effort": 459.64,
        "level": 0.2,
        "bugs": 0.03,
        "time": 26,
        "intelligentContent": 18.39,
        "number_operators": 9,
        "number_operands": 20,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 35,
        "loc": 70,
        "lloc": 35,
        "mi": 96.89,
        "mIwoC": 52.44,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.61,
        "relativeSystemComplexity": 5.61,
        "totalStructuralComplexity": 24,
        "totalDataComplexity": 9.67,
        "totalSystemComplexity": 33.67,
        "package": "App\\Player\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]